-- INSERT INTO users (name, photo, email, password) VALUES ('Tobias Funke', 'https://picsum.photos/200', 'blueManGroup@hotmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');

INSERT INTO users (name, photo, email, password) VALUES
('Michael Bluth', '/images/users/1.png', 'michael.bluth@example.com', 'password'),
('Lucille Bluth', '/images/users/2.png', 'lucille.bluth@example.com', 'password'),
('Leslie Knope', '/images/users/3.png', 'leslie.knope@example.com', 'password'),
('Ron Swanson', '/images/users/4.png', 'ron.swanson@example.com', 'password'),
('Jim Halpert', '/images/users/5.png', 'jim.halpert@example.com', 'password'),
('Pam Beesly', '/images/users/6.png', 'pam.beesly@example.com', 'password'),
('Nandor The Relentless', '/images/users/7.png', 'nandor.relentless@example.com', 'password'),
('Lazlo Cravensworth', '/images/users/8.png', 'lazlo.cravensworth@example.com', 'password'),
('Tobias Funke', '/images/users/9.png', 'tobias.funke@example.com', 'password'),
('George Michael Bluth', '/images/users/10.png', 'george.michael@example.com', 'password'),
('April Ludgate', '/images/users/11.png', 'april.ludgate@example.com', 'password'),
('Andy Dwyer', '/images/users/12.png', 'andy.dwyer@example.com', 'password'),
('Dwight Schrute', '/images/users/13.png', 'dwight.schrute@example.com', 'password'),
('Michael Scott', '/images/users/14.png', 'michael.scott@example.com', 'password'),
('Nadia', '/images/users/15.png', 'nadia@example.com', 'password'),
('Guillermo', '/images/users/16.png', 'guillermo@example.com', 'password'),
('Gob Bluth', '/images/users/17.png', 'gob.bluth@example.com', 'password'),
('Buster Bluth', '/images/users/18.png', 'buster.bluth@example.com', 'password'),
('Tom Haverford', '/images/users/19.png', 'tom.haverford@example.com', 'password'),
('Donna Meagle', '/images/users/20.png', 'donna.meagle@example.com', 'password');

insert into reviews (park_id, user_id, rating, review) values (1, 3, 1, 'Diverse');
insert into reviews (park_id, user_id, rating, review) values (74, 12, 5, 'installation');
insert into reviews (park_id, user_id, rating, review) values (87, 5, 2, 'Enhanced');
insert into reviews (park_id, user_id, rating, review) values (4, 14, 5, 'Graphic Interface');
insert into reviews (park_id, user_id, rating, review) values (107, 14, 3, 'structure');
insert into reviews (park_id, user_id, rating, review) values (67, 18, 2, 'hybrid');
insert into reviews (park_id, user_id, rating, review) values (38, 1, 3, 'utilisation');
insert into reviews (park_id, user_id, rating, review) values (99, 15, 2, 'intranet');
insert into reviews (park_id, user_id, rating, review) values (54, 2, 3, 'executive');
insert into reviews (park_id, user_id, rating, review) values (39, 9, 1, 'budgetary management');
insert into reviews (park_id, user_id, rating, review) values (75, 12, 2, 'web-enabled');
insert into reviews (park_id, user_id, rating, review) values (119, 19, 3, 'Digitized');
insert into reviews (park_id, user_id, rating, review) values (19, 10, 5, 'Profound');
insert into reviews (park_id, user_id, rating, review) values (18, 18, 3, 'local area network');
insert into reviews (park_id, user_id, rating, review) values (120, 14, 4, 'orchestration');
insert into reviews (park_id, user_id, rating, review) values (30, 1, 1, 'methodology');
insert into reviews (park_id, user_id, rating, review) values (116, 20, 4, 'time-frame');
insert into reviews (park_id, user_id, rating, review) values (4, 19, 2, 'Mandatory');
insert into reviews (park_id, user_id, rating, review) values (32, 5, 5, 'asynchronous');
insert into reviews (park_id, user_id, rating, review) values (89, 7, 4, 'Synergistic');
insert into reviews (park_id, user_id, rating, review) values (24, 14, 2, 'Digitized');
insert into reviews (park_id, user_id, rating, review) values (76, 14, 1, 'Managed');
insert into reviews (park_id, user_id, rating, review) values (65, 9, 1, 'service-desk');
insert into reviews (park_id, user_id, rating, review) values (14, 10, 1, 'Team-oriented');
insert into reviews (park_id, user_id, rating, review) values (38, 18, 3, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (102, 13, 5, 'multi-tasking');
insert into reviews (park_id, user_id, rating, review) values (47, 17, 4, 'Horizontal');
insert into reviews (park_id, user_id, rating, review) values (99, 16, 3, 'Optimized');
insert into reviews (park_id, user_id, rating, review) values (59, 4, 5, 'radical');
insert into reviews (park_id, user_id, rating, review) values (24, 8, 4, 'homogeneous');
insert into reviews (park_id, user_id, rating, review) values (30, 12, 4, 'heuristic');
insert into reviews (park_id, user_id, rating, review) values (70, 4, 2, 'attitude');
insert into reviews (park_id, user_id, rating, review) values (71, 19, 1, 'Upgradable');
insert into reviews (park_id, user_id, rating, review) values (12, 7, 3, 'hub');
insert into reviews (park_id, user_id, rating, review) values (100, 10, 1, 'bottom-line');
insert into reviews (park_id, user_id, rating, review) values (24, 6, 5, 'background');
insert into reviews (park_id, user_id, rating, review) values (91, 16, 2, 'Profound');
insert into reviews (park_id, user_id, rating, review) values (10, 20, 2, 'moderator');
insert into reviews (park_id, user_id, rating, review) values (70, 3, 5, 'emulation');
insert into reviews (park_id, user_id, rating, review) values (46, 18, 2, 'system engine');
insert into reviews (park_id, user_id, rating, review) values (14, 10, 1, 'firmware');
insert into reviews (park_id, user_id, rating, review) values (53, 13, 4, 'dedicated');
insert into reviews (park_id, user_id, rating, review) values (103, 17, 3, 'neural-net');
insert into reviews (park_id, user_id, rating, review) values (78, 13, 3, 'conglomeration');
insert into reviews (park_id, user_id, rating, review) values (28, 1, 4, 'migration');
insert into reviews (park_id, user_id, rating, review) values (64, 5, 2, 'Visionary');
insert into reviews (park_id, user_id, rating, review) values (10, 2, 2, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (85, 20, 4, 'Grass-roots');
insert into reviews (park_id, user_id, rating, review) values (70, 4, 4, 'reciprocal');
insert into reviews (park_id, user_id, rating, review) values (5, 18, 3, 'capability');
insert into reviews (park_id, user_id, rating, review) values (45, 6, 1, 'Synergistic');
insert into reviews (park_id, user_id, rating, review) values (24, 20, 2, 'product');
insert into reviews (park_id, user_id, rating, review) values (108, 10, 5, 'Automated');
insert into reviews (park_id, user_id, rating, review) values (41, 1, 4, 'Cross-group');
insert into reviews (park_id, user_id, rating, review) values (61, 14, 1, 'customer loyalty');
insert into reviews (park_id, user_id, rating, review) values (81, 10, 3, 'functionalities');
insert into reviews (park_id, user_id, rating, review) values (33, 16, 3, 'Decentralized');
insert into reviews (park_id, user_id, rating, review) values (35, 10, 3, 'stable');
insert into reviews (park_id, user_id, rating, review) values (79, 4, 1, 'content-based');
insert into reviews (park_id, user_id, rating, review) values (4, 10, 3, 'Monitored');
insert into reviews (park_id, user_id, rating, review) values (91, 11, 2, 'holistic');
insert into reviews (park_id, user_id, rating, review) values (110, 13, 5, 'Extended');
insert into reviews (park_id, user_id, rating, review) values (17, 17, 2, 'systemic');
insert into reviews (park_id, user_id, rating, review) values (55, 8, 4, 'groupware');
insert into reviews (park_id, user_id, rating, review) values (57, 16, 3, 'multi-tasking');
insert into reviews (park_id, user_id, rating, review) values (113, 15, 2, 'toolset');
insert into reviews (park_id, user_id, rating, review) values (74, 9, 4, 'Team-oriented');
insert into reviews (park_id, user_id, rating, review) values (19, 1, 4, 'De-engineered');
insert into reviews (park_id, user_id, rating, review) values (110, 6, 5, 'process improvement');
insert into reviews (park_id, user_id, rating, review) values (17, 6, 3, 'capacity');
insert into reviews (park_id, user_id, rating, review) values (113, 18, 5, 'algorithm');
insert into reviews (park_id, user_id, rating, review) values (42, 15, 1, 'groupware');
insert into reviews (park_id, user_id, rating, review) values (78, 3, 2, 'Fundamental');
insert into reviews (park_id, user_id, rating, review) values (115, 2, 4, 'Adaptive');
insert into reviews (park_id, user_id, rating, review) values (24, 12, 4, 'parallelism');
insert into reviews (park_id, user_id, rating, review) values (37, 20, 3, 'Diverse');
insert into reviews (park_id, user_id, rating, review) values (94, 3, 3, 'holistic');
insert into reviews (park_id, user_id, rating, review) values (49, 16, 1, 'transitional');
insert into reviews (park_id, user_id, rating, review) values (83, 7, 4, 'web-enabled');
insert into reviews (park_id, user_id, rating, review) values (89, 16, 1, 'project');
insert into reviews (park_id, user_id, rating, review) values (22, 4, 1, 'migration');
insert into reviews (park_id, user_id, rating, review) values (67, 1, 5, 'service-desk');
insert into reviews (park_id, user_id, rating, review) values (33, 5, 3, 'Focused');
insert into reviews (park_id, user_id, rating, review) values (94, 13, 2, 'function');
insert into reviews (park_id, user_id, rating, review) values (97, 15, 5, 'Cloned');
insert into reviews (park_id, user_id, rating, review) values (47, 8, 5, 'Up-sized');
insert into reviews (park_id, user_id, rating, review) values (28, 16, 2, 'parallelism');
insert into reviews (park_id, user_id, rating, review) values (48, 13, 4, 'Ergonomic');
insert into reviews (park_id, user_id, rating, review) values (55, 8, 2, 'customer loyalty');
insert into reviews (park_id, user_id, rating, review) values (31, 15, 2, 'Profound');
insert into reviews (park_id, user_id, rating, review) values (111, 20, 1, 'Reverse-engineered');
insert into reviews (park_id, user_id, rating, review) values (96, 5, 1, 'bottom-line');
insert into reviews (park_id, user_id, rating, review) values (97, 4, 3, 'infrastructure');
insert into reviews (park_id, user_id, rating, review) values (19, 8, 3, 'migration');
insert into reviews (park_id, user_id, rating, review) values (46, 12, 4, 'Inverse');
insert into reviews (park_id, user_id, rating, review) values (45, 15, 2, 'leading edge');
insert into reviews (park_id, user_id, rating, review) values (75, 12, 1, 'Realigned');
insert into reviews (park_id, user_id, rating, review) values (42, 17, 5, 'clear-thinking');
insert into reviews (park_id, user_id, rating, review) values (74, 11, 2, 'Cross-group');
insert into reviews (park_id, user_id, rating, review) values (66, 3, 2, 'project');
insert into reviews (park_id, user_id, rating, review) values (54, 15, 3, 'analyzer');
insert into reviews (park_id, user_id, rating, review) values (64, 16, 3, 'zero tolerance');
insert into reviews (park_id, user_id, rating, review) values (56, 20, 4, 'Assimilated');
insert into reviews (park_id, user_id, rating, review) values (86, 19, 2, 'strategy');
insert into reviews (park_id, user_id, rating, review) values (45, 6, 2, 'clear-thinking');
insert into reviews (park_id, user_id, rating, review) values (41, 15, 2, 'Reduced');
insert into reviews (park_id, user_id, rating, review) values (2, 16, 3, 'neutral');
insert into reviews (park_id, user_id, rating, review) values (85, 20, 4, 'disintermediate');
insert into reviews (park_id, user_id, rating, review) values (117, 8, 1, 'Open-architected');
insert into reviews (park_id, user_id, rating, review) values (57, 11, 3, 'info-mediaries');
insert into reviews (park_id, user_id, rating, review) values (55, 5, 3, 'attitude');
insert into reviews (park_id, user_id, rating, review) values (48, 3, 2, 'capability');
insert into reviews (park_id, user_id, rating, review) values (33, 17, 5, 'didactic');
insert into reviews (park_id, user_id, rating, review) values (68, 14, 3, 'task-force');
insert into reviews (park_id, user_id, rating, review) values (14, 11, 3, 'matrix');
insert into reviews (park_id, user_id, rating, review) values (72, 4, 3, 'Upgradable');
insert into reviews (park_id, user_id, rating, review) values (80, 19, 2, 'Integrated');
insert into reviews (park_id, user_id, rating, review) values (61, 12, 4, 'artificial intelligence');
insert into reviews (park_id, user_id, rating, review) values (45, 19, 2, 'analyzer');
insert into reviews (park_id, user_id, rating, review) values (81, 15, 4, 'matrices');
insert into reviews (park_id, user_id, rating, review) values (24, 20, 5, 'definition');
insert into reviews (park_id, user_id, rating, review) values (8, 14, 1, 'paradigm');
insert into reviews (park_id, user_id, rating, review) values (118, 13, 2, 'implementation');
insert into reviews (park_id, user_id, rating, review) values (94, 5, 3, 'ability');
insert into reviews (park_id, user_id, rating, review) values (19, 4, 1, 'Reverse-engineered');
insert into reviews (park_id, user_id, rating, review) values (110, 5, 4, 'disintermediate');
insert into reviews (park_id, user_id, rating, review) values (109, 3, 3, 'framework');
insert into reviews (park_id, user_id, rating, review) values (90, 16, 3, 'matrices');
insert into reviews (park_id, user_id, rating, review) values (120, 14, 1, 'architecture');
insert into reviews (park_id, user_id, rating, review) values (32, 3, 3, 'demand-driven');
insert into reviews (park_id, user_id, rating, review) values (104, 16, 1, 'motivating');
insert into reviews (park_id, user_id, rating, review) values (1, 11, 4, 'Graphical User Interface');
insert into reviews (park_id, user_id, rating, review) values (79, 1, 1, 'Streamlined');
insert into reviews (park_id, user_id, rating, review) values (51, 8, 1, 'focus group');
insert into reviews (park_id, user_id, rating, review) values (30, 19, 3, 'Switchable');
insert into reviews (park_id, user_id, rating, review) values (61, 11, 4, 'bifurcated');
insert into reviews (park_id, user_id, rating, review) values (28, 10, 3, 'contingency');
insert into reviews (park_id, user_id, rating, review) values (78, 20, 3, 'client-driven');
insert into reviews (park_id, user_id, rating, review) values (56, 1, 1, 'attitude-oriented');
insert into reviews (park_id, user_id, rating, review) values (25, 11, 1, 'logistical');
insert into reviews (park_id, user_id, rating, review) values (5, 10, 5, 'bifurcated');
insert into reviews (park_id, user_id, rating, review) values (37, 9, 1, 'Managed');
insert into reviews (park_id, user_id, rating, review) values (84, 5, 1, 'high-level');
insert into reviews (park_id, user_id, rating, review) values (79, 5, 1, 'exuding');
insert into reviews (park_id, user_id, rating, review) values (84, 17, 1, 'system-worthy');
insert into reviews (park_id, user_id, rating, review) values (29, 1, 2, 'Advanced');
insert into reviews (park_id, user_id, rating, review) values (81, 3, 5, 'extranet');
insert into reviews (park_id, user_id, rating, review) values (43, 9, 5, 'secured line');
insert into reviews (park_id, user_id, rating, review) values (30, 15, 2, 'workforce');
insert into reviews (park_id, user_id, rating, review) values (47, 20, 3, 'well-modulated');
insert into reviews (park_id, user_id, rating, review) values (117, 13, 4, 'help-desk');
insert into reviews (park_id, user_id, rating, review) values (120, 15, 4, 'Reverse-engineered');
insert into reviews (park_id, user_id, rating, review) values (82, 18, 1, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (83, 20, 5, 'Face to face');
insert into reviews (park_id, user_id, rating, review) values (103, 14, 3, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (74, 14, 5, 'Ameliorated');
insert into reviews (park_id, user_id, rating, review) values (83, 2, 4, 'Advanced');
insert into reviews (park_id, user_id, rating, review) values (88, 5, 5, 'function');
insert into reviews (park_id, user_id, rating, review) values (89, 12, 5, 'system engine');
insert into reviews (park_id, user_id, rating, review) values (19, 10, 3, 'multi-state');
insert into reviews (park_id, user_id, rating, review) values (94, 5, 1, '4th generation');
insert into reviews (park_id, user_id, rating, review) values (105, 11, 2, 'monitoring');
insert into reviews (park_id, user_id, rating, review) values (59, 7, 3, 'paradigm');
insert into reviews (park_id, user_id, rating, review) values (72, 6, 3, 'User-centric');
insert into reviews (park_id, user_id, rating, review) values (56, 2, 3, 'Seamless');
insert into reviews (park_id, user_id, rating, review) values (66, 2, 4, 'Managed');
insert into reviews (park_id, user_id, rating, review) values (120, 10, 2, 'Business-focused');
insert into reviews (park_id, user_id, rating, review) values (53, 14, 3, 'Phased');
insert into reviews (park_id, user_id, rating, review) values (114, 6, 3, 'migration');
insert into reviews (park_id, user_id, rating, review) values (67, 3, 1, 'disintermediate');
insert into reviews (park_id, user_id, rating, review) values (13, 7, 3, 'moderator');
insert into reviews (park_id, user_id, rating, review) values (103, 7, 5, 'pricing structure');
insert into reviews (park_id, user_id, rating, review) values (107, 13, 3, 'uniform');
insert into reviews (park_id, user_id, rating, review) values (81, 15, 3, 'Total');
insert into reviews (park_id, user_id, rating, review) values (63, 14, 5, 'algorithm');
insert into reviews (park_id, user_id, rating, review) values (32, 1, 2, 'multi-state');
insert into reviews (park_id, user_id, rating, review) values (98, 9, 3, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (77, 5, 3, 'Ameliorated');
insert into reviews (park_id, user_id, rating, review) values (74, 18, 2, 'Profound');
insert into reviews (park_id, user_id, rating, review) values (28, 12, 2, 'Polarised');
insert into reviews (park_id, user_id, rating, review) values (47, 16, 4, 'frame');
insert into reviews (park_id, user_id, rating, review) values (66, 14, 1, 'User-friendly');
insert into reviews (park_id, user_id, rating, review) values (77, 10, 4, 'client-driven');
insert into reviews (park_id, user_id, rating, review) values (45, 13, 1, 'capability');
insert into reviews (park_id, user_id, rating, review) values (16, 20, 1, 'empowering');
insert into reviews (park_id, user_id, rating, review) values (15, 4, 2, 'directional');
insert into reviews (park_id, user_id, rating, review) values (20, 10, 1, 'disintermediate');
insert into reviews (park_id, user_id, rating, review) values (110, 7, 5, 'optimizing');
insert into reviews (park_id, user_id, rating, review) values (9, 18, 3, 'Open-architected');
insert into reviews (park_id, user_id, rating, review) values (3, 7, 4, 'non-volatile');
insert into reviews (park_id, user_id, rating, review) values (27, 3, 1, 'system engine');
insert into reviews (park_id, user_id, rating, review) values (107, 16, 3, 'model');
insert into reviews (park_id, user_id, rating, review) values (97, 11, 5, 'analyzer');
insert into reviews (park_id, user_id, rating, review) values (77, 12, 1, 'Persistent');
insert into reviews (park_id, user_id, rating, review) values (88, 15, 1, 'Advanced');
insert into reviews (park_id, user_id, rating, review) values (82, 2, 4, 'core');
insert into reviews (park_id, user_id, rating, review) values (68, 16, 2, 'definition');
insert into reviews (park_id, user_id, rating, review) values (9, 13, 3, 'uniform');
insert into reviews (park_id, user_id, rating, review) values (50, 7, 4, 'implementation');
insert into reviews (park_id, user_id, rating, review) values (5, 18, 5, 'support');
insert into reviews (park_id, user_id, rating, review) values (16, 3, 2, 'scalable');
insert into reviews (park_id, user_id, rating, review) values (105, 3, 2, 'matrices');
insert into reviews (park_id, user_id, rating, review) values (9, 8, 5, 'Reactive');
insert into reviews (park_id, user_id, rating, review) values (95, 8, 2, 'alliance');
insert into reviews (park_id, user_id, rating, review) values (107, 13, 3, 'synergy');
insert into reviews (park_id, user_id, rating, review) values (85, 13, 1, 'Public-key');
insert into reviews (park_id, user_id, rating, review) values (50, 1, 3, 'intangible');
insert into reviews (park_id, user_id, rating, review) values (76, 9, 5, 'Object-based');
insert into reviews (park_id, user_id, rating, review) values (14, 7, 2, 'User-friendly');
insert into reviews (park_id, user_id, rating, review) values (113, 7, 5, 'open architecture');
insert into reviews (park_id, user_id, rating, review) values (91, 9, 1, 'needs-based');
insert into reviews (park_id, user_id, rating, review) values (42, 9, 1, 'systemic');
insert into reviews (park_id, user_id, rating, review) values (87, 7, 5, 'homogeneous');
insert into reviews (park_id, user_id, rating, review) values (101, 19, 1, 'tangible');
insert into reviews (park_id, user_id, rating, review) values (112, 8, 4, 'Centralized');
insert into reviews (park_id, user_id, rating, review) values (56, 4, 2, 'User-friendly');
insert into reviews (park_id, user_id, rating, review) values (27, 5, 2, 'dedicated');
insert into reviews (park_id, user_id, rating, review) values (62, 18, 1, 'Decentralized');
insert into reviews (park_id, user_id, rating, review) values (87, 6, 4, 'policy');
insert into reviews (park_id, user_id, rating, review) values (29, 11, 1, 'asymmetric');
insert into reviews (park_id, user_id, rating, review) values (26, 12, 5, 'firmware');
insert into reviews (park_id, user_id, rating, review) values (18, 7, 1, 'directional');
insert into reviews (park_id, user_id, rating, review) values (45, 12, 1, 'pricing structure');
insert into reviews (park_id, user_id, rating, review) values (80, 16, 5, 'national');
insert into reviews (park_id, user_id, rating, review) values (44, 1, 1, 'high-level');
insert into reviews (park_id, user_id, rating, review) values (89, 18, 1, '3rd generation');
insert into reviews (park_id, user_id, rating, review) values (30, 5, 5, 'Multi-layered');
insert into reviews (park_id, user_id, rating, review) values (35, 9, 5, 'support');
insert into reviews (park_id, user_id, rating, review) values (39, 6, 2, 'discrete');
insert into reviews (park_id, user_id, rating, review) values (94, 1, 5, 'Function-based');
insert into reviews (park_id, user_id, rating, review) values (40, 14, 2, 'mobile');
insert into reviews (park_id, user_id, rating, review) values (71, 3, 3, 'global');
insert into reviews (park_id, user_id, rating, review) values (41, 11, 1, 'local area network');
insert into reviews (park_id, user_id, rating, review) values (108, 19, 2, 'ability');
insert into reviews (park_id, user_id, rating, review) values (11, 4, 1, 'Assimilated');
insert into reviews (park_id, user_id, rating, review) values (78, 4, 3, 'parallelism');
insert into reviews (park_id, user_id, rating, review) values (115, 11, 2, 'leverage');
insert into reviews (park_id, user_id, rating, review) values (44, 6, 1, 'Open-source');
insert into reviews (park_id, user_id, rating, review) values (113, 20, 2, 'open architecture');
insert into reviews (park_id, user_id, rating, review) values (6, 17, 2, 'model');
insert into reviews (park_id, user_id, rating, review) values (66, 10, 5, 'challenge');
insert into reviews (park_id, user_id, rating, review) values (78, 13, 5, 'foreground');
insert into reviews (park_id, user_id, rating, review) values (75, 11, 3, 'leverage');
insert into reviews (park_id, user_id, rating, review) values (65, 15, 3, 'Team-oriented');
insert into reviews (park_id, user_id, rating, review) values (45, 1, 5, 'process improvement');
insert into reviews (park_id, user_id, rating, review) values (104, 5, 1, 'installation');
insert into reviews (park_id, user_id, rating, review) values (43, 3, 5, 'encoding');
insert into reviews (park_id, user_id, rating, review) values (27, 3, 3, 'Multi-tiered');
insert into reviews (park_id, user_id, rating, review) values (98, 5, 3, 'Automated');
insert into reviews (park_id, user_id, rating, review) values (11, 17, 2, 'static');
insert into reviews (park_id, user_id, rating, review) values (48, 8, 5, 'background');
insert into reviews (park_id, user_id, rating, review) values (100, 17, 3, 'functionalities');
insert into reviews (park_id, user_id, rating, review) values (69, 8, 4, 'global');
insert into reviews (park_id, user_id, rating, review) values (27, 18, 5, 'impactful');
insert into reviews (park_id, user_id, rating, review) values (104, 6, 5, 'conglomeration');
insert into reviews (park_id, user_id, rating, review) values (95, 8, 2, 'Graphical User Interface');
insert into reviews (park_id, user_id, rating, review) values (78, 10, 1, 'contingency');
insert into reviews (park_id, user_id, rating, review) values (120, 10, 5, 'Self-enabling');
insert into reviews (park_id, user_id, rating, review) values (100, 15, 3, 'matrix');
insert into reviews (park_id, user_id, rating, review) values (48, 18, 5, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (30, 18, 2, 'reciprocal');
insert into reviews (park_id, user_id, rating, review) values (59, 15, 1, 'utilisation');
insert into reviews (park_id, user_id, rating, review) values (108, 5, 2, 'intermediate');
insert into reviews (park_id, user_id, rating, review) values (98, 10, 1, 'non-volatile');
insert into reviews (park_id, user_id, rating, review) values (11, 1, 2, 'Integrated');
insert into reviews (park_id, user_id, rating, review) values (50, 5, 5, 'Automated');
insert into reviews (park_id, user_id, rating, review) values (69, 19, 1, 'optimal');
insert into reviews (park_id, user_id, rating, review) values (116, 17, 4, 'open architecture');
insert into reviews (park_id, user_id, rating, review) values (39, 4, 3, 'attitude');
insert into reviews (park_id, user_id, rating, review) values (87, 8, 1, 'Devolved');
insert into reviews (park_id, user_id, rating, review) values (105, 20, 5, 'throughput');
insert into reviews (park_id, user_id, rating, review) values (73, 1, 4, 'multi-state');
insert into reviews (park_id, user_id, rating, review) values (72, 2, 5, 'initiative');
insert into reviews (park_id, user_id, rating, review) values (74, 16, 3, 'asynchronous');
insert into reviews (park_id, user_id, rating, review) values (47, 16, 3, 'toolset');
insert into reviews (park_id, user_id, rating, review) values (31, 7, 5, 'dedicated');
insert into reviews (park_id, user_id, rating, review) values (46, 5, 1, 'regional');
insert into reviews (park_id, user_id, rating, review) values (6, 20, 2, 'eco-centric');
insert into reviews (park_id, user_id, rating, review) values (38, 16, 5, 'solution');
insert into reviews (park_id, user_id, rating, review) values (22, 11, 3, 'Re-engineered');
insert into reviews (park_id, user_id, rating, review) values (6, 13, 3, 'software');
insert into reviews (park_id, user_id, rating, review) values (74, 20, 1, 'Compatible');
insert into reviews (park_id, user_id, rating, review) values (65, 19, 2, 'Balanced');
insert into reviews (park_id, user_id, rating, review) values (7, 17, 2, 'Intuitive');
insert into reviews (park_id, user_id, rating, review) values (13, 15, 2, 'Multi-tiered');
insert into reviews (park_id, user_id, rating, review) values (65, 4, 4, 'Extended');
insert into reviews (park_id, user_id, rating, review) values (65, 18, 3, 'Reactive');
insert into reviews (park_id, user_id, rating, review) values (50, 19, 4, 'Front-line');
insert into reviews (park_id, user_id, rating, review) values (55, 6, 3, 'composite');
insert into reviews (park_id, user_id, rating, review) values (24, 12, 2, 'algorithm');
insert into reviews (park_id, user_id, rating, review) values (55, 11, 3, 'bottom-line');
insert into reviews (park_id, user_id, rating, review) values (83, 8, 3, 'concept');
insert into reviews (park_id, user_id, rating, review) values (116, 9, 3, 'model');
insert into reviews (park_id, user_id, rating, review) values (101, 14, 4, 'implementation');
insert into reviews (park_id, user_id, rating, review) values (17, 6, 4, 'value-added');
insert into reviews (park_id, user_id, rating, review) values (99, 8, 2, 'Enterprise-wide');
insert into reviews (park_id, user_id, rating, review) values (59, 16, 3, 'upward-trending');
insert into reviews (park_id, user_id, rating, review) values (88, 10, 2, 'ability');
insert into reviews (park_id, user_id, rating, review) values (62, 2, 2, 'protocol');
insert into reviews (park_id, user_id, rating, review) values (83, 3, 2, 'Expanded');
insert into reviews (park_id, user_id, rating, review) values (77, 2, 3, 'local');
insert into reviews (park_id, user_id, rating, review) values (109, 17, 1, 'approach');
insert into reviews (park_id, user_id, rating, review) values (38, 18, 5, 'service-desk');
insert into reviews (park_id, user_id, rating, review) values (42, 4, 2, 'project');
insert into reviews (park_id, user_id, rating, review) values (56, 17, 1, 'hub');
insert into reviews (park_id, user_id, rating, review) values (52, 7, 3, 'Organic');
insert into reviews (park_id, user_id, rating, review) values (24, 1, 3, 'strategy');
insert into reviews (park_id, user_id, rating, review) values (58, 3, 2, 'zero administration');
insert into reviews (park_id, user_id, rating, review) values (113, 15, 4, 'system-worthy');
insert into reviews (park_id, user_id, rating, review) values (79, 4, 4, 'concept');
insert into reviews (park_id, user_id, rating, review) values (94, 3, 3, 'application');
insert into reviews (park_id, user_id, rating, review) values (96, 13, 1, 'protocol');
insert into reviews (park_id, user_id, rating, review) values (77, 17, 4, 'orchestration');
insert into reviews (park_id, user_id, rating, review) values (59, 18, 2, 'model');
insert into reviews (park_id, user_id, rating, review) values (8, 11, 1, 'paradigm');
insert into reviews (park_id, user_id, rating, review) values (80, 16, 1, 'bandwidth-monitored');
insert into reviews (park_id, user_id, rating, review) values (71, 1, 5, 'incremental');
insert into reviews (park_id, user_id, rating, review) values (45, 13, 1, 'directional');
insert into reviews (park_id, user_id, rating, review) values (48, 15, 5, 'help-desk');
insert into reviews (park_id, user_id, rating, review) values (117, 18, 1, 'Optimized');
insert into reviews (park_id, user_id, rating, review) values (89, 4, 1, 'Intuitive');
insert into reviews (park_id, user_id, rating, review) values (31, 20, 3, 'Progressive');
insert into reviews (park_id, user_id, rating, review) values (57, 9, 4, 'interface');
insert into reviews (park_id, user_id, rating, review) values (114, 9, 1, 'Seamless');
insert into reviews (park_id, user_id, rating, review) values (18, 11, 4, 'system engine');
insert into reviews (park_id, user_id, rating, review) values (87, 7, 1, 'Seamless');
insert into reviews (park_id, user_id, rating, review) values (34, 16, 4, 'Adaptive');
insert into reviews (park_id, user_id, rating, review) values (36, 16, 3, 'project');
insert into reviews (park_id, user_id, rating, review) values (7, 6, 5, 'Operative');
insert into reviews (park_id, user_id, rating, review) values (1, 5, 5, 'motivating');
insert into reviews (park_id, user_id, rating, review) values (36, 13, 2, 'Vision-oriented');
insert into reviews (park_id, user_id, rating, review) values (41, 15, 4, 'upward-trending');
insert into reviews (park_id, user_id, rating, review) values (51, 17, 1, 'Sharable');
insert into reviews (park_id, user_id, rating, review) values (85, 10, 5, 'neutral');
insert into reviews (park_id, user_id, rating, review) values (35, 6, 1, 'emulation');
insert into reviews (park_id, user_id, rating, review) values (108, 17, 5, 'Expanded');
insert into reviews (park_id, user_id, rating, review) values (92, 15, 3, 'Total');
insert into reviews (park_id, user_id, rating, review) values (68, 6, 4, 'orchestration');
insert into reviews (park_id, user_id, rating, review) values (28, 1, 3, 'Secured');
insert into reviews (park_id, user_id, rating, review) values (19, 7, 3, 'adapter');
insert into reviews (park_id, user_id, rating, review) values (53, 4, 5, 'disintermediate');
insert into reviews (park_id, user_id, rating, review) values (2, 18, 1, 'zero tolerance');
insert into reviews (park_id, user_id, rating, review) values (108, 17, 5, 'actuating');
insert into reviews (park_id, user_id, rating, review) values (72, 9, 5, 'system-worthy');
insert into reviews (park_id, user_id, rating, review) values (66, 4, 2, 'Phased');
insert into reviews (park_id, user_id, rating, review) values (26, 4, 3, 'solution-oriented');
insert into reviews (park_id, user_id, rating, review) values (58, 5, 1, 'bandwidth-monitored');
insert into reviews (park_id, user_id, rating, review) values (100, 10, 3, 'Compatible');
insert into reviews (park_id, user_id, rating, review) values (50, 12, 3, 'Networked');
insert into reviews (park_id, user_id, rating, review) values (93, 1, 2, 'Operative');
insert into reviews (park_id, user_id, rating, review) values (57, 1, 3, 'national');
insert into reviews (park_id, user_id, rating, review) values (97, 4, 1, 'tertiary');
insert into reviews (park_id, user_id, rating, review) values (77, 6, 4, 'Enhanced');
insert into reviews (park_id, user_id, rating, review) values (28, 17, 1, 'frame');
insert into reviews (park_id, user_id, rating, review) values (17, 9, 1, 'logistical');
insert into reviews (park_id, user_id, rating, review) values (82, 6, 1, 'secured line');
insert into reviews (park_id, user_id, rating, review) values (32, 12, 5, 'upward-trending');
insert into reviews (park_id, user_id, rating, review) values (88, 18, 5, 'maximized');
insert into reviews (park_id, user_id, rating, review) values (62, 7, 4, 'Diverse');
insert into reviews (park_id, user_id, rating, review) values (31, 17, 4, 'Pre-emptive');
insert into reviews (park_id, user_id, rating, review) values (50, 7, 5, 'Sharable');
insert into reviews (park_id, user_id, rating, review) values (90, 2, 1, 'Face to face');
insert into reviews (park_id, user_id, rating, review) values (46, 1, 4, 'Adaptive');
insert into reviews (park_id, user_id, rating, review) values (28, 20, 3, 'multi-state');
insert into reviews (park_id, user_id, rating, review) values (76, 5, 1, 'system-worthy');
insert into reviews (park_id, user_id, rating, review) values (55, 6, 5, 'Expanded');
insert into reviews (park_id, user_id, rating, review) values (113, 2, 1, 'Visionary');
insert into reviews (park_id, user_id, rating, review) values (65, 1, 3, 'Digitized');
insert into reviews (park_id, user_id, rating, review) values (106, 19, 5, 'uniform');
insert into reviews (park_id, user_id, rating, review) values (31, 2, 3, 'Balanced');
insert into reviews (park_id, user_id, rating, review) values (115, 9, 5, 'incremental');
insert into reviews (park_id, user_id, rating, review) values (5, 12, 4, 'interface');
insert into reviews (park_id, user_id, rating, review) values (92, 18, 1, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (27, 4, 3, 'Up-sized');
insert into reviews (park_id, user_id, rating, review) values (83, 11, 1, 'concept');
insert into reviews (park_id, user_id, rating, review) values (98, 19, 1, 'Proactive');
insert into reviews (park_id, user_id, rating, review) values (4, 16, 5, 'national');
insert into reviews (park_id, user_id, rating, review) values (66, 19, 1, 'mobile');
insert into reviews (park_id, user_id, rating, review) values (29, 14, 1, 'Grass-roots');
insert into reviews (park_id, user_id, rating, review) values (116, 11, 2, 'Persevering');
insert into reviews (park_id, user_id, rating, review) values (37, 18, 5, 'background');
insert into reviews (park_id, user_id, rating, review) values (15, 1, 5, 'Realigned');
insert into reviews (park_id, user_id, rating, review) values (52, 5, 5, 'Diverse');
insert into reviews (park_id, user_id, rating, review) values (77, 6, 2, 'definition');
insert into reviews (park_id, user_id, rating, review) values (115, 13, 2, 'encoding');
insert into reviews (park_id, user_id, rating, review) values (27, 20, 5, 'Expanded');
insert into reviews (park_id, user_id, rating, review) values (26, 10, 1, 'modular');
insert into reviews (park_id, user_id, rating, review) values (47, 9, 1, 'analyzing');
insert into reviews (park_id, user_id, rating, review) values (98, 12, 5, 'Customizable');
insert into reviews (park_id, user_id, rating, review) values (26, 13, 3, 'Customizable');
insert into reviews (park_id, user_id, rating, review) values (19, 16, 2, 'Upgradable');
insert into reviews (park_id, user_id, rating, review) values (57, 16, 4, 'attitude');
insert into reviews (park_id, user_id, rating, review) values (113, 14, 4, 'client-driven');
insert into reviews (park_id, user_id, rating, review) values (98, 7, 1, 'User-friendly');
insert into reviews (park_id, user_id, rating, review) values (35, 3, 2, 'hybrid');
insert into reviews (park_id, user_id, rating, review) values (88, 6, 5, 'Organic');
insert into reviews (park_id, user_id, rating, review) values (54, 8, 5, 'Virtual');
insert into reviews (park_id, user_id, rating, review) values (117, 1, 3, 'migration');
insert into reviews (park_id, user_id, rating, review) values (1, 12, 2, 'Universal');
insert into reviews (park_id, user_id, rating, review) values (45, 11, 5, 'well-modulated');
insert into reviews (park_id, user_id, rating, review) values (74, 4, 3, 'client-driven');
insert into reviews (park_id, user_id, rating, review) values (52, 9, 1, 'Assimilated');
insert into reviews (park_id, user_id, rating, review) values (71, 7, 1, 'impactful');
insert into reviews (park_id, user_id, rating, review) values (45, 5, 1, 'success');
insert into reviews (park_id, user_id, rating, review) values (109, 5, 3, 'functionalities');
insert into reviews (park_id, user_id, rating, review) values (39, 17, 1, 'flexibility');
insert into reviews (park_id, user_id, rating, review) values (64, 5, 3, 'stable');
insert into reviews (park_id, user_id, rating, review) values (23, 8, 4, 'Visionary');
insert into reviews (park_id, user_id, rating, review) values (118, 15, 2, 'heuristic');
insert into reviews (park_id, user_id, rating, review) values (16, 2, 4, 'background');
insert into reviews (park_id, user_id, rating, review) values (27, 4, 5, 'context-sensitive');
insert into reviews (park_id, user_id, rating, review) values (59, 7, 4, 'protocol');
insert into reviews (park_id, user_id, rating, review) values (84, 18, 4, 'Focused');
insert into reviews (park_id, user_id, rating, review) values (51, 3, 5, 'national');
insert into reviews (park_id, user_id, rating, review) values (35, 2, 2, 'Up-sized');
insert into reviews (park_id, user_id, rating, review) values (120, 13, 4, 'explicit');
insert into reviews (park_id, user_id, rating, review) values (9, 18, 3, 'fresh-thinking');
insert into reviews (park_id, user_id, rating, review) values (118, 20, 2, 'Advanced');
insert into reviews (park_id, user_id, rating, review) values (2, 8, 3, 'leading edge');
insert into reviews (park_id, user_id, rating, review) values (62, 19, 1, 'Pre-emptive');
insert into reviews (park_id, user_id, rating, review) values (81, 11, 5, 'budgetary management');
insert into reviews (park_id, user_id, rating, review) values (89, 6, 5, 'motivating');
insert into reviews (park_id, user_id, rating, review) values (86, 10, 5, 'global');
insert into reviews (park_id, user_id, rating, review) values (116, 4, 1, 'Synergistic');
insert into reviews (park_id, user_id, rating, review) values (77, 13, 5, 'systematic');
insert into reviews (park_id, user_id, rating, review) values (93, 12, 2, 'Re-contextualized');
insert into reviews (park_id, user_id, rating, review) values (49, 15, 1, 'Fully-configurable');
insert into reviews (park_id, user_id, rating, review) values (45, 16, 3, 'ability');
insert into reviews (park_id, user_id, rating, review) values (85, 2, 2, 'interface');
insert into reviews (park_id, user_id, rating, review) values (94, 20, 3, 'well-modulated');
insert into reviews (park_id, user_id, rating, review) values (41, 15, 4, 'orchestration');
insert into reviews (park_id, user_id, rating, review) values (87, 7, 4, 'background');
insert into reviews (park_id, user_id, rating, review) values (66, 16, 4, 'clear-thinking');
insert into reviews (park_id, user_id, rating, review) values (38, 1, 2, 'Open-architected');
insert into reviews (park_id, user_id, rating, review) values (113, 3, 3, 'coherent');
insert into reviews (park_id, user_id, rating, review) values (72, 14, 3, 'Organic');
insert into reviews (park_id, user_id, rating, review) values (70, 12, 2, 'Integrated');
insert into reviews (park_id, user_id, rating, review) values (78, 2, 3, 'Optional');
insert into reviews (park_id, user_id, rating, review) values (112, 8, 5, 'complexity');
insert into reviews (park_id, user_id, rating, review) values (37, 6, 2, 'archive');
insert into reviews (park_id, user_id, rating, review) values (60, 3, 4, 'Triple-buffered');
insert into reviews (park_id, user_id, rating, review) values (61, 3, 2, 'contextually-based');
insert into reviews (park_id, user_id, rating, review) values (115, 2, 3, 'conglomeration');
insert into reviews (park_id, user_id, rating, review) values (36, 6, 4, 'contextually-based');
insert into reviews (park_id, user_id, rating, review) values (77, 6, 3, 'exuding');
insert into reviews (park_id, user_id, rating, review) values (107, 5, 5, 'budgetary management');
insert into reviews (park_id, user_id, rating, review) values (64, 10, 1, 'Versatile');
insert into reviews (park_id, user_id, rating, review) values (33, 16, 1, 'executive');
insert into reviews (park_id, user_id, rating, review) values (73, 10, 5, 'projection');
insert into reviews (park_id, user_id, rating, review) values (114, 17, 3, 'Multi-lateral');
insert into reviews (park_id, user_id, rating, review) values (9, 3, 5, 'full-range');
insert into reviews (park_id, user_id, rating, review) values (22, 9, 2, 'instruction set');
insert into reviews (park_id, user_id, rating, review) values (35, 10, 4, 'Synergistic');
insert into reviews (park_id, user_id, rating, review) values (27, 11, 4, 'contingency');
insert into reviews (park_id, user_id, rating, review) values (59, 15, 1, '3rd generation');
insert into reviews (park_id, user_id, rating, review) values (89, 3, 2, 'core');
insert into reviews (park_id, user_id, rating, review) values (18, 16, 2, 'scalable');
insert into reviews (park_id, user_id, rating, review) values (7, 16, 2, 'challenge');
insert into reviews (park_id, user_id, rating, review) values (97, 20, 2, 'contingency');
insert into reviews (park_id, user_id, rating, review) values (88, 19, 5, 'Synergized');
insert into reviews (park_id, user_id, rating, review) values (108, 7, 4, 'Grass-roots');
insert into reviews (park_id, user_id, rating, review) values (42, 14, 1, 'concept');
insert into reviews (park_id, user_id, rating, review) values (58, 7, 2, 'asymmetric');
insert into reviews (park_id, user_id, rating, review) values (16, 11, 4, 'methodical');
insert into reviews (park_id, user_id, rating, review) values (88, 2, 5, 'matrices');
insert into reviews (park_id, user_id, rating, review) values (6, 17, 4, 'capability');
insert into reviews (park_id, user_id, rating, review) values (68, 20, 3, 'didactic');
insert into reviews (park_id, user_id, rating, review) values (75, 20, 5, 'installation');
insert into reviews (park_id, user_id, rating, review) values (104, 11, 1, 'value-added');
insert into reviews (park_id, user_id, rating, review) values (38, 9, 2, 'hierarchy');
insert into reviews (park_id, user_id, rating, review) values (20, 7, 3, 'Function-based');
insert into reviews (park_id, user_id, rating, review) values (85, 4, 4, 'synergy');
insert into reviews (park_id, user_id, rating, review) values (98, 19, 1, 'disintermediate');
insert into reviews (park_id, user_id, rating, review) values (31, 15, 2, 'collaboration');
insert into reviews (park_id, user_id, rating, review) values (20, 6, 1, 'system-worthy');
insert into reviews (park_id, user_id, rating, review) values (47, 13, 5, 'Implemented');
insert into reviews (park_id, user_id, rating, review) values (54, 2, 3, 'uniform');
insert into reviews (park_id, user_id, rating, review) values (95, 4, 5, 'Implemented');
insert into reviews (park_id, user_id, rating, review) values (33, 9, 3, 'Multi-layered');
insert into reviews (park_id, user_id, rating, review) values (21, 2, 5, 'Secured');
insert into reviews (park_id, user_id, rating, review) values (1, 17, 2, 'Balanced');
insert into reviews (park_id, user_id, rating, review) values (53, 9, 3, 'policy');
insert into reviews (park_id, user_id, rating, review) values (99, 9, 3, 'impactful');
insert into reviews (park_id, user_id, rating, review) values (41, 14, 2, 'Balanced');
insert into reviews (park_id, user_id, rating, review) values (97, 12, 4, 'Distributed');
insert into reviews (park_id, user_id, rating, review) values (43, 7, 2, 'adapter');
insert into reviews (park_id, user_id, rating, review) values (7, 14, 2, 'User-centric');
insert into reviews (park_id, user_id, rating, review) values (71, 11, 5, 'system-worthy');
insert into reviews (park_id, user_id, rating, review) values (62, 7, 4, 'Seamless');
insert into reviews (park_id, user_id, rating, review) values (48, 12, 2, 'pricing structure');
insert into reviews (park_id, user_id, rating, review) values (57, 13, 2, 'systematic');
insert into reviews (park_id, user_id, rating, review) values (114, 8, 4, 'application');
insert into reviews (park_id, user_id, rating, review) values (91, 19, 5, 'orchestration');
insert into reviews (park_id, user_id, rating, review) values (58, 6, 1, 'budgetary management');
insert into reviews (park_id, user_id, rating, review) values (97, 9, 4, 'Centralized');
insert into reviews (park_id, user_id, rating, review) values (107, 9, 1, 'Implemented');
insert into reviews (park_id, user_id, rating, review) values (112, 3, 1, 'Re-engineered');
insert into reviews (park_id, user_id, rating, review) values (106, 5, 1, 'Adaptive');
insert into reviews (park_id, user_id, rating, review) values (111, 2, 1, '24/7');
insert into reviews (park_id, user_id, rating, review) values (5, 20, 3, 'Multi-channelled');

